#Basic
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,5])

In [ ]:
print(a)

[1 2 3 5]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],
              [1,5,6]])

In [ ]:
print(b)

[[[1 2 3]
  [1 5 6]
  [1 2 3]]]


In [ ]:
c= np.array([1,2,3],dtype=complex)

In [ ]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

#Attributes

In [ ]:
a = np.array([[1,2,3],[7,8,9]])

In [ ]:
print(a)

[[1 2 3]
 [7 8 9]]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
#resize array
a.shape=(3,2)

In [ ]:
a

array([[1, 2],
       [3, 7],
       [8, 9]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a.shape= (6,1)

In [ ]:
a

array([[1],
       [2],
       [3],
       [7],
       [8],
       [9]])

In [ ]:
a.shape = (8,1)

ValueError: cannot reshape array of size 6 into shape (8,1)

In [ ]:
a = np.arange(24)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.ndim

1

In [ ]:
a = np.arange(6)
b = a.reshape(2,3)
print(a)
print("------------------")
print(b)

[0 1 2 3 4 5]
------------------
[[0 1 2]
 [3 4 5]]


In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c = a.reshape(2,6,2)
c.ndim

3

In [ ]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
x = np.array([1,2,3,5,6],dtype=np.int8)
x.itemsize

NameError: name 'np' is not defined

In [ ]:
y = np.array([1,2,3,5,6],dtype=np.float32)
y.itemsize

4

#Array Creation

In [1]:
a = np.empty([3,2])
print(a)

NameError: name 'np' is not defined

In [3]:
import numpy as np
x = np.zeros(2)

print(x)

[0. 0.]


In [ ]:
x = np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x = np.ones((2,2))
print(x)

[[1. 1.]
 [1. 1.]]


In [4]:
b = np.identity(2)
print(b.shape)
print(b)

(2, 2)
[[1. 0.]
 [0. 1.]]


#asarray

In [ ]:
x = [1,2,3]
print(type(x))
a = np.asarray(x)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
x = (1,2,3)
print(type(x))
a = np.asarray(x)
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
x = [(12,3,6),(7,8,9)]
print(type(x))
a = np.asarray(x)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
x = {1:55, 2:78}
print(type(x))
a = np.asarray(x)
print(type(a))
print(a)

<class 'dict'>
<class 'numpy.ndarray'>
{1: 55, 2: 78}


#np.fromiter

In [ ]:
a = range(5)
print(a)

range(0, 5)


In [ ]:
for x in a:
  print(x)

In [ ]:
x = np.fromiter(a,dtype=float)
print(x)
print(type(x))

[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [ ]:
c = np.array(a)
c

array([0, 1, 2, 3, 4])

#Numpy array from multiple ranges

In [10]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
x = np.linspace(0,10,11)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [12]:
a = np.zeros((2,2))
print(a)
b = np.ones((2,2))
print(b)
c = np.eye(2)
print(c)
d = np.full((2,2),8)
print(d)
e =np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[8 8]
 [8 8]]
[[0.4914261  0.41460787]
 [0.9308844  0.02717592]]


#Array indexing

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],
 [11,12,13,14,15],
              [16,17,18,19,20]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[-2:,-2:]

array([[14, 15],
       [19, 20]])

In [ ]:
a[-2:,-2:] = np.array([[55,55],[66,66]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 55 55]
 [16 17 18 66 66]]


In [ ]:
a = np.array([[1,2],[3,4],[4,5]])
print(a)

[[1 2]
 [3 4]
 [4 5]]


In [ ]:
print(a>2)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print(a[a>2])

[3 4 4 5]


#Math

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [ ]:
y

array([[5, 6],
       [7, 8]])

In [ ]:
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [ ]:
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(np.sum(x))

21


In [ ]:
print(np.sum(x,axis=0))

[5 7 9]


In [ ]:
print(np.sum(x,axis=1))

[ 6 15]


In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = x.T
print(y)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
x = np.array([[1,2],[7,8]])


In [ ]:
y = np.linalg.inv(x)
print(y)

[[-1.33333333  0.33333333]
 [ 1.16666667 -0.16666667]]


In [ ]:
x.dot(y)

array([[1., 0.],
       [0., 1.]])

#Broadcasting

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

In [ ]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
v

array([1, 0, 1])

In [ ]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [ ]:
8x1+3x2+5x3+2x4 = 45
2x1+8x2+6x3+x4 = 55
x1+x2+8x3+x4 = 66
x1+x2+2x3 + 6x4 = 12

In [ ]:
x 1     2    3   5    9    15    25
y 0.2   0.3  0.6 0.8  1.2  1.6   2.1

x = 6